[[redirects]]
from = "/discord"
to = "https://discordapp.com/invite/t8K7NtA"
status = 301

[[redirects]]
from = "/zoom"
to = "https://us04web.zoom.us/j/7762156646?pwd=RVFFSEVXNU1RQUpVRkRieXBJc3I4Zz09"
status = 301

[[redirects]]
from = "*"
to = "/404/"
status = 404

